variables:
  CI_DEBUG_TRACE: "false"

stages:
  - build
  - push

build:
  stage: build
  script:
    - docker buildx build -t $CI_REGISTRY_IMAGE:latest -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG --push . --platform linux/amd64,linux/arm64 --provenance false
  only:
    - tags

push:
  stage: push
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    AWS_REGION: "eu-central-1"
    TAG: '-t ${AWS_ECR}/jmeter:latest'
    PLATFORM: "linux/arm64"
    DOCKERFILE: "Dockerfile"
  script:
    - >
      if [ -n "$AWS_ACCESS_KEY_ID" ] && [ -n "$AWS_SECRET_ACCESS_KEY" ]; then
        $(aws ecr get-login --no-include-email --region $AWS_REGION)
      fi
    - >
      if [ -n "$DOCKER_REGISTRY_USER" ] && [ -n "$DOCKER_REGISTRY_PASSWORD" ] && [ -n "$DOCKER_REGISTRY_URL" ]; then
        docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY_URL
      fi
    - docker buildx build ${TAG} -f ${DOCKERFILE} . --push --platform ${PLATFORM}
  only:
    - tags